### ISSUE TITLE
JSR107 tck tests fail on master branch

### ISSUE THREAD

**Issue by nicoloboschi** [diennea/blazingcache#70]
Every tests failed with this error:
`Expecting no open client connections. Customizations implementing Closeable need to be closed. See https://github.com/jsr107/jsr107tck/issues/100`

**Comment by eolivelli** [comment]
Created an issue against the TCK https://github.com/jsr107/jsr107tck/issues/134

**Comment by eolivelli** [comment]
closed with 258588fefc06db48f935f4e3a340a4f87add3308
